### PR TITLE
fix deprecation warnings for 0.4rc2

### PR DESCRIPTION
**Pull request by rened**
String -> AbstractString
Nothing -> Void
Union(...) -> Union{...}

### CODE REVIEW

**Comment by nolta** [comment]
Thanks!

**Comment by garborg** [comment]
This broke Winston on 0.3 (and 0.2) by using new syntax like `Union{...}` without wrapping it with `@compat`. Using Compat would bring back 0.3 compatibility, but I'm not sure about 0.2 compatibility.

**Comment by rened** [comment]
Thanks, will fix immediately. Sorry for that.

**Comment by garborg** [comment]
No worries, thanks for the quick response, @rened.

**Pull request merged**
