### PR TITLE
adding @compat for 0.3

### PR DESCRIPTION
**Pull request by rened**
Fix #240 for 0.3 by using `@compat` for `Void` and `Union{...}`

### CODE REVIEW

**Comment by rened** [comment]
cc @garborg - could you test this as well, please?

**Comment by garborg** [comment]
Looks fixed on Travis. It seems no OSX run has ever been successful because they can't find `xvfb-run` -- perhaps remove `osx` from `.travis.yml`?

**Comment by garborg** [comment]
Looking good to me.

**Comment by nolta** [comment]
Thanks!

**Pull request merged**
