### PR TITLE
Updates for Julia 0.7, drop 0.5 and 0.6

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like the remaining 0.7 failure is the fault of Tk:
```
ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: UndefVarError: JULIA_HOME not defined
Stacktrace:
 [1] init() at /home/travis/.julia/v0.7/Tk/src/tkwidget.jl:35
```

**Comment by tknopp** [comment]
@ararslan this is extremely interesting. If 0.7 is running: what do you get timings for the first plot (see https://github.com/JuliaLang/julia/issues/27083 for the issue I am talking about)

Regarding the remaining 0.7 fault I would simply disable Tk.

**Comment by tknopp** [comment]
After #288 is merged it would be interesting if tests are passing then @ararslan. Lets get this package all green in CI testing!

**Comment by tknopp** [comment]
@ararslan: I have some further fixes for your branch `aa/updates`. Can you give me commit access so that I can push them?

**Comment by tknopp** [comment]
@ararslan: thanks!!!

Are you fine with dropping 0.6 support in Winston?

**Comment by ararslan** [comment]
Yes, and I think it is likely necessary in order to support 1.0 fully.

**Comment by tknopp** [comment]
Yep, but I will need help for non-trivial issues in Gtk:
   https://github.com/JuliaGraphics/Gtk.jl/issues/358

The other really urgent thing is to fix the Homebrew issue that makes `Cairo.jl` failing. This propagates through all these packages.

**Comment by tknopp** [comment]
@ararslan: I still do not have commit access here in Winston, although I am team member of JuliaGraphics. I think you need to "manage my access" if you click on me in the group menu.

**Comment by ararslan** [comment]
You should have write access now

**Comment by tknopp** [comment]
great works. I have create `release-julia-0.6` as our 0.6 branch. Will push my fixes to `aa/updates` and push that branch to master then.

**Comment by ararslan** [comment]
Sure, just want to make sure it passes CI before merging to master

**Comment by tknopp** [comment]
Of course. Although I would only look at 0.7 linux, since 1.0 and mac will not pass

**Comment by tknopp** [comment]
(funnily enough I am doing this on a mac, but fixed the Homebrew thingy manually)

**Pull request merged**
