### PR TITLE
Use travis testing on Winston

### PR DESCRIPTION
**Pull request by timholy**
@nolta, for this to work you'll have to go to https://travis-ci.org/profile and "flip the switch" on Winston. Only owners (i.e., you) can do that.

### CODE REVIEW

**Comment by timholy** [comment]
Note the use of `xvfb-run`, because the Travis servers run without a display.

**Comment by nolta** [comment]
Thanks!

**Comment by timholy** [comment]
Hmm, looks like #222 still failed due to some permissions problem. I seem to recall that there are some settings on this repository that need to be changed to allow Travis access? Maybe under Settings->Webhooks&Services->Services, add Travis?

**Comment by timholy** [comment]
@nolta, if you change that setting, maybe let @rened know? And then rebase and force-push to test? (Or just push a small test commit, @nolta, until the travis run passes.)

**Comment by rened** [comment]
@nolta fyi, you can also manually restart the travis for #222 on your travis page. Alternatively, one can use the following to trigger travis without changing anything, it just updates the timestamp:
```
git commit --amend
git push -f origin HEAD
```

**Comment by nolta** [comment]
That setting is/was enabled. Not sure what's going on.

**Comment by timholy** [comment]
I screwed up #222, see #223. Sorry about that---I grabbed from a repository of mine (ProfileView) that has not had as many commits as Winston, so the "shallow" issue hasn't yet triggered a problem.

**Pull request merged**
