### PR TITLE
fixes for 0.4

### PR DESCRIPTION
**Pull request by rened**
Needs https://github.com/JuliaLang/Compat.jl/pull/86 to pass all tests

### CODE REVIEW

**Comment by rened** [comment]
Updated, passes all tests on 0.4, on 0.3 example07 has a slight difference in the transition from red to blue.

**Comment by nolta** [comment]
Thanks! Do you understand the slight color difference?

**Comment by rened** [comment]
Unfortunately not - I just emailed you the image I get for example07.

**Comment by timholy** [comment]
I don't understand how this could have worked on 0.3 without `@compat Int(b)`. See problem reports in #218, #219, #220.

@rened, I not infrequently fool myself because I have a copy of package `X` in both `.julia/v0.3` and `.julia/v0.4`. If you're changing the source in the one in `v0.4`, then to test on 0.3 you have to say
```
~/.julia/v0.4/X/test$ julia-old
< 0.3 startup banner >
julia> include("../src/X.jl")

julia> include("runtests.jl")
```
That forces loading of your modified source code on 0.3 (i.e., 0.3 will use the package code in `v0.4`).

A better strategy, of course, is to get Travis working on Winston.

**Comment by rened** [comment]
@timholy You are right, I must have messed something up here, very sorry about that. I am looking into this.

**Comment by rened** [comment]
Fixed in #222, should close #218, #219, #220.

**Pull request merged**
