### PR TITLE
Fix on 0.3, using @compat

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by nolta** [comment]
@rened, could you rebase this branch against master?

**Comment by timholy** [comment]
Once this gets merged, it will be good to tag a new release.

**Comment by rened** [comment]
@nolta done

**Comment by tkelman** [comment]
Bump, would be good to tag a release that works on 0.3.

**Comment by timholy** [comment]
I hadn't noticed this never got done. See https://github.com/JuliaLang/METADATA.jl/pull/2655.

@nolta, I notice you haven't tagged anything in a while. It's now as easy as `Pkg.update(); Pkg.tag("Winston"); Pkg.publish()` and then click on the link that appears. Wait for the travis build to pass on your PR and merge.

**Pull request merged**
